<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>True</UseWindowsForms>
    <ApplicationIcon>Resources\Image\monkey-face-navy.ico</ApplicationIcon>
    <AssemblyVersion>2.1.1.0</AssemblyVersion>
    <FileVersion></FileVersion>
    <Version>2.1.1-ex.5</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Deterministic>False</Deterministic>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Deterministic>False</Deterministic>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Image\wows-numbers-icon.png" />
    <None Remove="Resources\Image\wows-official-icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Image\monkey-face-navy.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-beta.710" />
    <PackageReference Include="log4net" Version="2.0.15" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RestoreWindowPlace" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="log4net.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="README.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Json\ships.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Json\ships_en-us.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Json\ships_zh-cn.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Json\expected_values.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="WatchList.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Image\wows-numbers-icon.png" />
    <Resource Include="Resources\Image\wows-official-icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\Json\" />
  </ItemGroup>

</Project>
