//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApeRadar.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.1.1-ex.1")]
        public string SoftwareVersion {
            get {
                return ((string)(this["SoftwareVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20260831")]
        public string SoftwareDate {
            get {
                return ((string)(this["SoftwareDate"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsUpgradeDone {
            get {
                return ((bool)(this["SettingsUpgradeDone"]));
            }
            set {
                this["SettingsUpgradeDone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUTO")]
        public string Server {
            get {
                return ((string)(this["Server"]));
            }
            set {
                this["Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SecondaryServerEnabled {
            get {
                return ((bool)(this["SecondaryServerEnabled"]));
            }
            set {
                this["SecondaryServerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EU")]
        public string SecondaryServer {
            get {
                return ((string)(this["SecondaryServer"]));
            }
            set {
                this["SecondaryServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GamePath {
            get {
                return ((string)(this["GamePath"]));
            }
            set {
                this["GamePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUTO")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AUTO")]
        public string ShipNameLanguage {
            get {
                return ((string)(this["ShipNameLanguage"]));
            }
            set {
                this["ShipNameLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MaximumRetryAttemptsOnError {
            get {
                return ((int)(this["MaximumRetryAttemptsOnError"]));
            }
            set {
                this["MaximumRetryAttemptsOnError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForUpdatesOnStartup {
            get {
                return ((bool)(this["CheckForUpdatesOnStartup"]));
            }
            set {
                this["CheckForUpdatesOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ColorStyle {
            get {
                return ((int)(this["ColorStyle"]));
            }
            set {
                this["ColorStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("🐵")]
        public string ApeIcon {
            get {
                return ((string)(this["ApeIcon"]));
            }
            set {
                this["ApeIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("🏅")]
        public string UnicumIcon {
            get {
                return ((string)(this["UnicumIcon"]));
            }
            set {
                this["UnicumIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("🚫")]
        public string HiddenIcon {
            get {
                return ((string)(this["HiddenIcon"]));
            }
            set {
                this["HiddenIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("⚠️")]
        public string WatchIcon {
            get {
                return ((string)(this["WatchIcon"]));
            }
            set {
                this["WatchIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AccountWinrateVisibility {
            get {
                return ((int)(this["AccountWinrateVisibility"]));
            }
            set {
                this["AccountWinrateVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WeightedWinrateVisibility {
            get {
                return ((int)(this["WeightedWinrateVisibility"]));
            }
            set {
                this["WeightedWinrateVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ShipWinrateVisibility {
            get {
                return ((int)(this["ShipWinrateVisibility"]));
            }
            set {
                this["ShipWinrateVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TagVisibility {
            get {
                return ((int)(this["TagVisibility"]));
            }
            set {
                this["TagVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AccountAvgExpVisibility {
            get {
                return ((int)(this["AccountAvgExpVisibility"]));
            }
            set {
                this["AccountAvgExpVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ShipAvgExpVisibility {
            get {
                return ((int)(this["ShipAvgExpVisibility"]));
            }
            set {
                this["ShipAvgExpVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ShipAvgDmgVisibility {
            get {
                return ((int)(this["ShipAvgDmgVisibility"]));
            }
            set {
                this["ShipAvgDmgVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PRVisibility {
            get {
                return ((int)(this["PRVisibility"]));
            }
            set {
                this["PRVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public double PlayerColumnFontSize {
            get {
                return ((double)(this["PlayerColumnFontSize"]));
            }
            set {
                this["PlayerColumnFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double StatisticsColumnFontSize {
            get {
                return ((double)(this["StatisticsColumnFontSize"]));
            }
            set {
                this["StatisticsColumnFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double DetailedStatisticsFontSize {
            get {
                return ((double)(this["DetailedStatisticsFontSize"]));
            }
            set {
                this["DetailedStatisticsFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public double OutputTextFontSize {
            get {
                return ((double)(this["OutputTextFontSize"]));
            }
            set {
                this["OutputTextFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnemiesDisplayMirrored {
            get {
                return ((bool)(this["EnemiesDisplayMirrored"]));
            }
            set {
                this["EnemiesDisplayMirrored"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PlayerListSortBy {
            get {
                return ((int)(this["PlayerListSortBy"]));
            }
            set {
                this["PlayerListSortBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlayerNamesVisibility {
            get {
                return ((bool)(this["PlayerNamesVisibility"]));
            }
            set {
                this["PlayerNamesVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int WinrateChartType {
            get {
                return ((int)(this["WinrateChartType"]));
            }
            set {
                this["WinrateChartType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WinrateTypeUsed {
            get {
                return ((int)(this["WinrateTypeUsed"]));
            }
            set {
                this["WinrateTypeUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("47")]
        public double ApeWinrateThreshold {
            get {
                return ((double)(this["ApeWinrateThreshold"]));
            }
            set {
                this["ApeWinrateThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ApeBattleCountThreshold {
            get {
                return ((int)(this["ApeBattleCountThreshold"]));
            }
            set {
                this["ApeBattleCountThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("58")]
        public double UnicumWinrateThreshold {
            get {
                return ((double)(this["UnicumWinrateThreshold"]));
            }
            set {
                this["UnicumWinrateThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int UnicumBattleCountThreshold {
            get {
                return ((int)(this["UnicumBattleCountThreshold"]));
            }
            set {
                this["UnicumBattleCountThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double WeightedWinrateAccountSoloWeightMultiplier {
            get {
                return ((double)(this["WeightedWinrateAccountSoloWeightMultiplier"]));
            }
            set {
                this["WeightedWinrateAccountSoloWeightMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double WeightedWinrateAccountDiv2WeightMultiplier {
            get {
                return ((double)(this["WeightedWinrateAccountDiv2WeightMultiplier"]));
            }
            set {
                this["WeightedWinrateAccountDiv2WeightMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double WeightedWinrateAccountDiv3WeightMultiplier {
            get {
                return ((double)(this["WeightedWinrateAccountDiv3WeightMultiplier"]));
            }
            set {
                this["WeightedWinrateAccountDiv3WeightMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double WeightedWinrateShipMaxWeight {
            get {
                return ((double)(this["WeightedWinrateShipMaxWeight"]));
            }
            set {
                this["WeightedWinrateShipMaxWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int WeightedWinrateShipBattlesAtMaxWeight {
            get {
                return ((int)(this["WeightedWinrateShipBattlesAtMaxWeight"]));
            }
            set {
                this["WeightedWinrateShipBattlesAtMaxWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("我方上等马：{AllyUnicumList}。我方下等马：{AllyApeList}。我方隐藏马：{AllyHiddenList}。敌方上等马：{EnemyUni" +
            "cumList}。敌方下等马：{EnemyApeList}。敌方隐藏马：{EnemyHiddenList}。战绩插件加群1012624096。")]
        public string OutputTextTemplateGeneralStatistics {
            get {
                return ((string)(this["OutputTextTemplateGeneralStatistics"]));
            }
            set {
                this["OutputTextTemplateGeneralStatistics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputTextDelimiter {
            get {
                return ((string)(this["OutputTextDelimiter"]));
            }
            set {
                this["OutputTextDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OutputTextShortMode {
            get {
                return ((bool)(this["OutputTextShortMode"]));
            }
            set {
                this["OutputTextShortMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutputTextExcludeSelf {
            get {
                return ((bool)(this["OutputTextExcludeSelf"]));
            }
            set {
                this["OutputTextExcludeSelf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutputTextUnlock {
            get {
                return ((bool)(this["OutputTextUnlock"]));
            }
            set {
                this["OutputTextUnlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OutputTextAutoCopy {
            get {
                return ((bool)(this["OutputTextAutoCopy"]));
            }
            set {
                this["OutputTextAutoCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{ClanTag} {PlayerName}（{ShipName}），账号{AccountBattles}场 {AccountWinrate}胜率，单船{Ship" +
            "Battles}场 {ShipWinrate}胜率 {ShipAvgDmg}场均。战绩插件加群1012624096。")]
        public string OutputTextTemplateParticularPlayerStatistics {
            get {
                return ((string)(this["OutputTextTemplateParticularPlayerStatistics"]));
            }
            set {
                this["OutputTextTemplateParticularPlayerStatistics"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VORTEX")]
        public string APITypeSelection {
            get {
                return ((string)(this["APITypeSelection"]));
            }
            set {
                this["APITypeSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool YuyukoAPIPushEnabled {
            get {
                return ((bool)(this["YuyukoAPIPushEnabled"]));
            }
            set {
                this["YuyukoAPIPushEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugMode {
            get {
                return ((bool)(this["DebugMode"]));
            }
            set {
                this["DebugMode"] = value;
            }
        }
    }
}
